services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # your app connects here (AMQP protocol)
      - "15672:15672" # web UI: open http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: behavioral_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123" # HTTP API: your Node.js client uses this
      - "9000:9000" # native protocol
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: "password"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  clickhouse_data:
